### ISSUE TITLE
Changing user settings changes user id

### ISSUE THREAD

**Issue by bgoncharuck** [rimmer/My-Horoskope#28]
When we try to change the user settings it changes the user id. Because fields in settings are changing user model on which id is calculated.

**Comment by bgoncharuck** [comment]
I will try to calculate id hash based only on a birthdate.
It still will be changed if user change his birth date, but at least it has more common sense.

**Comment by bgoncharuck** [comment]
# Important

If you will save any users data, all users with same date of birth will have same id.
How to solve this:
If you want to save polls for example, you need to save array of polls, then get arithmetic mean of it.

Even better if user polls are synced with network only if they are not exist locally.

**Comment by rimmer** [comment]
If the user changes setting it changes their I'd: what's the downside of it? This is how we identify the user. We don't have any other way to identify

UPD: After discussing with @bgoncharuck: because if we associate some values like votes. In that case keeping user id = birth date is not so bad idea
